package exception_handling

fun main(Args:Array<String>){
     val a =10/0
     println(a)
}